# Generated by Django 2.1.3 on 2018-11-18 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.IntegerField(choices=[(0, 'text'), (1, 'number'), (2, 'date'), (3, 'enum')], default=0)),
                ('slug', models.SlugField(editable=False)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('display_order', models.IntegerField(default=0, help_text='Display order for this field within the risk form. If two fields have the same order value, it will be resolved by the alphabetic order of their"name" value.')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='fieldtype',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='risks.RiskType'),
        ),
    ]
