# Generated by Django 2.1.3 on 2018-11-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_fieldtype_enum_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtype',
            name='enum_options',
            field=models.CharField(blank=True, default='', help_text='Helper for enums, comma separated list of desired options', max_length=1000),
        ),
    ]
