# Generated by Django 2.1.3 on 2018-11-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.IntegerField(choices=[(0, 'text'), (1, 'number'), (2, 'date'), (3, 'enum')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='fieldtype',
            name='risk',
            field=models.ManyToManyField(blank=True, related_name='fields', to='risks.RiskType'),
        ),
    ]
