version: '3'

services:

  app:
    build: ./
    command: gunicorn britecore_application.wsgi:application --bind 0.0.0.0:8000 -w 4
    ports:
      - 80:8000
    environment:
      - SECRET_KEY=Zy/KXWW+9zIKkIbrcEYmDjdvqgDgE6BvXGEbmwbreQBnax7tlt0HqDpsUkvckP6jLQ4=
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DB=postgres
      - SQL_PORT=5432
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=db
      - DATABASE=postgres
      - DJANGO_SETTINGS_MODULE=britecore_application.settings_prod
    depends_on:
      - db
  
  db:
    image: postgres:10.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
