version: '3'

services:

  app:
    build:
      context: ./services/app
      dockerfile: Dockerfile
    command: gunicorn britecore_application.wsgi:application --bind 0.0.0.0:8000 -w 4
    volumes:
      - './:/usr/src/app'
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=Zy/KXWW+9zIKkIbrcEYmDjdvqgDgE6BvXGEbmwbreQBnax7tlt0HqDpsUkvckP6jLQ4=
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=risks_dbuser
      - POSTGRES_PASSWORD=O[ex*U]k,#LI/IAwjtW7GA1<J
      - POSTGRES_DB=risks_db
    depends_on:
      - db
  
  db:
    image: postgres:10.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=risks_dbuser
      - POSTGRES_PASSWORD=O[ex*U]k,#LI/IAwjtW7GA1<J

  nginx:
    build: ./services/nginx
    volumes:
      - static:/usr/src/frontend/dist
    ports:
      - 8080
    depends_on:
      - backend

volumes:
  postgres_data:
  static: