version: '3'

services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn britecore_application.wsgi:application --bind 0.0.0.0:8000 -w 4
    volumes:
      - './:/usr/src/app'
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=Zy/KXWW+9zIKkIbrcEYmDjdvqgDgE6BvXGEbmwbreQBnax7tlt0HqDpsUkvckP6jLQ4=
      - SQL_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - DATABASE=postgres
    depends_on:
      - db
  
  db:
    image: postgres:10.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
  static: