# Generated by Django 2.1.3 on 2018-11-16 04:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.IntegerField(choices=[(0, 'text'), (1, 'number'), (2, 'date'), (3, 'enum')], default=0)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('number_of_fields', models.PositiveSmallIntegerField(blank=True, default=1, help_text='Enum (data_type==3) only. Number of fields to display', validators=[django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='fieldtype',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='risks.RiskType'),
        ),
    ]
