"""
Django settings for britecore_application project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

from .settings import *
SECRET_KEY = os.getenv('SECRET_KEY', None)

DEBUG = False

ALLOWED_HOSTS = ['localhost', '0.0.0.0', '.amazonaws.com']


